trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'my-custom-name'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'dockerHub'
    command: 'build'
    Dockerfile: 'app/Dockerfile'

- task: Docker@2
  displayName: Login
  inputs:
    containerRegistry: 'dockerHub'
    command: 'login'

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: 'dockerHub'
    repository: 'devops-test'
    command: 'push'

- task: Docker@2
  displayName: Logout
  inputs:
    containerRegistry: dockerHub
    command: 'logout'
