trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'my-custom-name'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'dockerHub'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: 'app/Dockerfile'
    tags: 'nazwa1'

- task: Docker@2
  displayName: Login
  inputs:
    containerRegistry: 'dockerHub'
    command: 'login'

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: 'dockerHub'
    repository: 'thedamik34/devops-test'
    command: 'push'
    tags: 'nazwa1'

- task: Docker@2
  displayName: Logout
  inputs:
    containerRegistry: dockerHub
    command: 'logout'
